pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@44.197.234.169 "
                            git config --global --add safe.directory /home/ubuntu/SHARP_GPT &&
                            cd /home/ubuntu/SHARP_GPT &&
                            git pull origin main
                        "
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@44.197.234.169 "
                            cd /home/ubuntu/SHARP_GPT/server &&
                            sudo docker compose down &&
                            sudo docker compose up --build -d &&
                            sudo docker image prune -f
                        "
                    '''
                }
            }
        }
    }

    post {
        success {
            echo '✅ Deployment successful!'
        }
        failure {
            echo '❌ Deployment failed!'
        }
    }
}